/* ---------- idea bank ---------- */
const FAM={
 1:{t:"Career outcomes for designers",v:"--f1"},
 2:{t:"Someone else pays",v:"--f2"},
 3:{t:"Sell to the market · newly possible",v:"--f3"},
 4:{t:"Format &amp; audience",v:"--f4"},
 5:{t:"Edges · geo, contrarian, anti-scale",v:"--f5"}};
const CL=[
{L:"A",f:1,t:"Sharpened core",w:"The obvious play, narrowed until it names a person",q:"Whose problem exactly?",i:[
[1,"The Aerospace-Grade Portfolio","Indian UX designers 2–5 yrs into agency work who keep losing enterprise roles get one safety-critical, dense-data case study. Nobody else in India can teach cockpit-grade complexity — you have the receipts.",0,0],
[2,"Enterprise UX Bootcamp (not consumer)","6-week cohort for designers tired of building food-delivery clones who want B2B and complex-systems roles. Indian UX teaching is overwhelmingly consumer-app craft, and complex-systems teaching barely exists. <span class='prov weak'>I could find no data on an enterprise-vs-consumer pay premium — I previously claimed 1.6× and that figure was invented. The nearest real number is a ~28% product-designer-over-UX-designer premium, which is not the same claim.</span>",0,0],
[3,"Design for Regulated Industries","Aviation, medical devices, energy, fintech compliance. Outcome: designers who can work inside standards like DO-178C and IEC 62366 — a credential literally no bootcamp offers.",0,0],
[4,"Strategic Design for Senior ICs","8 weeks for designers at 6–10 yrs who are done pushing pixels and want to lead. Your Polimi curriculum, translated. India has essentially zero strategic-design education.",0,0],
[5,"The Systems-Thinking Sprint","Designers and PMs who must present to leadership walk out with a systems map and a theory of change that fits on one slide.",0,0],
[6,"Portfolio Surgery, priced high","90-minute teardown plus a rewrite plan for designers targeting global roles. ₹8–15k. This is your cash-flow starter — live in two weeks, no build.",0,1],
[7,"Interview-Ready in 30 Days","Whiteboard-challenge drilling for Indian designers applying to global remote roles. Outcome: they run a live exercise without freezing.",0,1],
[8,"Case Study Writing Lab","Designers can design but cannot write. Outcome: three publishable case studies. Writing, not craft, is the actual bottleneck to getting hired.",0,1],
[9,"From Service to Product","Agency designers at TCS/Infosys/Zensar design arms making the jump to product companies. The mental-model shift, not the tool.",0,0],
[10,"The Milan Method","Repackage the Polimi strategic-design toolkit as an English-language paid toolkit for global designers. Credential arbitrage: EU method, India cost base.",0,1]]},
{L:"B",f:1,t:"Value-chain adjacency",w:"Before, during and after the core job — all unowned",q:"What happens either side?",i:[
[11,"Design Career Diagnostic","A paid 60-minute assessment plus written roadmap sold before anyone buys a course. Serves the undecided — the largest segment — and converts into everything downstream.",0,1],
[12,"The Pre-Bootcamp","A ₹999 two-week \"is UX actually for you?\" reality check for career switchers. Bootcamps waste lakhs on wrong-fit students; you monetise the filter.",0,1],
[13,"Placement-Only Service","No teaching at all. You take designers who already have the skill and get them hired. Fee on placement, from the employer.",1,0],
[14,"Portfolio-as-a-Service","Done-for-you portfolio build for working designers with no time. ₹40–80k, three weeks, no teaching involved.",0,0],
[15,"Résumé + LinkedIn Rewrite","Narrow, boring, ₹4k, high volume, fully templatable. Unglamorous businesses are the ones that pay next month.",0,1],
[16,"Salary Negotiation Coaching","Outcome: +₹4L on the offer. Fee is 10% of the increase. ROI is self-evident, so there is no trust barrier and no price objection.",0,1],
[17,"First-90-Days Retainer","New designers at a new job get weekly office hours so they don't fail probation. Recurring, low prep, high anxiety = high willingness to pay.",0,0],
[18,"Design Manager Onboarding Kit","For ICs just promoted to lead. The single most terrifying career transition in design, and nobody teaches it.",0,0],
[19,"Alumni Job Board + Referral Ring","A paid private network of vetted designers that companies pay to access. Runs on other people's success.",1,1],
[20,"Mock Interview Marketplace","You recruit senior designers as interviewers and take a cut. You are not the product and it scales past your calendar.",1,1],
[21,"Enterprise Portfolio Templates","Framer/Webflow templates built specifically for complex, data-dense case studies. Passive, evergreen, no delivery.",1,1],
[22,"Testimonial &amp; Proof Engine","A productized service that helps freelance designers collect and stage social proof. Boring, needed, repeatable.",0,1]]},
{L:"C",f:2,t:"Segment shift",w:"Change WHO — especially who signs the cheque",q:"Who else has this pain and a budget?",i:[
[23,"Enterprise Design Upskilling for GCCs","Sell the enterprise-UX curriculum to Indian global capability centres. The market is measured, not assumed: <b>1,750–2,100+ GCCs in India employing 1.9–2.3M professionals</b>, ~870 in Bengaluru alone, and an Indian corporate training market of <b>₹52,000 crore (2024) growing ~14% a year</b>. Specialist training in India bills <b>₹30,000–1.5L per day</b>. You already speak their language.",1,0],
[24,"Engineers Who Must Design","Train mechanical and software engineers at manufacturing firms to build usable HMIs. Employer pays. Enormous, almost entirely unserved market.",1,0],
[25,"Design Literacy for PMs","Product managers are judged on design quality and were never taught it. Company pays, cohort delivers, no portfolio anxiety involved.",1,0],
[26,"Founders' Design Sense","Non-design founders at seed-stage Indian startups stop shipping ugly and learn to brief a designer properly.",0,0],
[27,"Design for Sales Engineers","People who demo complex products learn to make their demos and decks legible. Sales orgs have budget and measure outcomes in revenue.",1,0],
[28,"Agency Owners' Ops Program","Teach 5–20 person Indian design agencies to sell strategy instead of hours. They have money and acute, specific pain.",0,0],
[29,"Corporate L&amp;D Workshops","Sell \"design thinking for innovation\" to L&D budgets rather than to individuals. That budget is annual, allocated, and must be spent before year end.",1,0],
[30,"B-School Elective","License a strategic-design module to ISB, SPJIMR, Masters' Union. Recurring, prestigious, and it builds the credential flywheel.",1,1],
[31,"Design Faculty Training","India's design colleges are staffed by underqualified faculty. Train the trainers; institutions pay from a capex-like budget.",1,0],
[32,"Career Clarity for Parents","The actual payer for a 17-year-old is their parent. A paid session for parents of design aspirants. Uncomfortable, and wildly underserved.",1,0],
[33,"NID / NIFT / UCEED Prep","Entrance-exam portfolio coaching. Parents pay, demand is price-insensitive and seasonal, and the market is enormous.",1,0],
[34,"Study-Abroad Design Applications","You got into Polimi — help Indian students get into EU and UK design masters. ₹50k–1.5L per applicant, parents pay, fully location-independent.",1,0],
]},
{L:"D",f:4,t:"Format &amp; experience shift",w:"Offline, live, physical, membership, event",q:"What if the format changed entirely?",i:[
[35,"Design Retreat, Goa or Bir","Four days, 20 designers, ₹45k each. Online is commoditised to zero. Presence isn't — but note it breaks your location-independence goal.",0,0],
[36,"The Roast, Live","Ticketed live event where portfolios get torn apart on stage. Every session becomes a month of content.",0,0],
[37,"India's Got Designers","A bracketed competition series. Sponsors pay, the winner gets a job. Be clear-eyed: it's a distribution machine disguised as a show — the show markets the business, it isn't the business.",1,0],
[38,"Hackathon-as-a-Service","Companies sponsor a weekend design challenge to recruit from it. You run it. Sponsor pays, designers attend free.",1,0],
[39,"Physical Method Card Deck","The Polimi strategic-design toolkit, printed, ₹2,500. Designers buy objects, margins are excellent, and it's a business card people pay for.",1,1],
[40,"The Book","A real published book on enterprise UX. Negligible revenue, enormous durable authority. Treat it as infrastructure, not income.",0,0],
[41,"Container, No Curriculum","No content whatsoever — a six-week cohort with deadlines, peer review and critique while designers do their own work. Completion is the product. The defensible version of the stat: peer-reviewed work puts median completion across 221 MOOCs at <b>12.6%</b>, and a Harvard study found <b>3.4× higher dropout</b> without peer or coach accountability. The 85–95% cohort figure comes from cohort-platform vendors — discount it.",0,0],
[42,"Office Hours Membership","₹999/month, two live calls a week, no curriculum to build or maintain. Recurring revenue, minimal prep.",0,0],
[43,"Async Video Critique","They upload, you return a 10-minute Loom within 48 hours. ₹3k each, batchable, timezone-proof, perfectly location-independent.",0,1],
[44,"The Design Gym","Weekly live drills, run like a fitness class. Same slot, same format, repeatable forever, no launch cycle.",0,0],
[45,"The Gated Podcast","A paid feed of unfiltered senior-designer conversations about salary, politics and layoffs — the things nobody says publicly.",0,0],
[46,"Studio Tour Series","Film inside studios in Milan, Copenhagen, Bangalore. Location independence as the product rather than a constraint.",0,0]]},
{L:"E",f:2,t:"Business-model shift",w:"Same delivery, different money",q:"Who pays, and when?",i:[
[47,"Employer-Sponsored Seats","Identical course, invoiced to the company instead of the learner. Three to five times the price, no discount-hunting, no EMI drama.",1,0],
[48,"Income-Share Placement","Free training, then 8% of salary for 12 months once placed above a floor. Capital-hungry, but it takes the price objection to literally zero.",1,0],
[49,"Sponsored Free Cohort","A design or AI tool pays you to teach 500 designers using their product. Tool vendors have large acquisition budgets and no credible educators.",1,0],
[50,"Take-Rate Marketplace","You don't teach. You curate senior Indian designers who do, and take 20–30%. Scales past your calendar entirely.",1,1],
[51,"License the Curriculum","Sell your enterprise-UX curriculum to bootcamps in other countries. Zero delivery obligation on your side.",1,1],
[52,"Become the Certification Body","Don't teach — assess and certify. Structurally the highest-margin position in any education market, and the one that survives when teaching commoditises. Requires an audience first.",1,1],
[53,"Corporate Advisory Retainer","One company, ₹2L a month, you are their part-time design-strategy voice. Two clients and you can resign.",1,0],
[54,"Equity for Design Strategy","Take 1–3% in seed-stage startups instead of fees. Lottery tickets, but free ones alongside paid work.",1,0],
[55,"Government / Skill-India Funding","NSDC-aligned design skilling has state budget attached. Bureaucratic and slow, but the cheque is large and it recurs.",1,0],
[56,"Affiliate-Funded Free Product","A genuinely free resource monetised by design-tool affiliate revenue. No customers to serve, no support load.",1,1]]},
{L:"F",f:3,t:"Picks &amp; shovels",w:"Sell to your competitors, not to their students",q:"Who's already spending to reach them?",i:[
[57,"Critique Tooling for Bootcamps","Every bootcamp runs critique manually and inconsistently. Sell them a structured critique and rubric platform.",1,1],
[58,"The Enterprise UX Question Bank","A licensed bank of interview questions and design exercises, sold to bootcamps and hiring teams.",1,1],
[59,"Hiring Assessment for Recruiters","Indian recruiters cannot evaluate design work. Sell them a scoring instrument. They have budget and no taste — that gap is the arbitrage.",1,1],
[60,"Cohort Ops Playbook","Sell the operational backbone — onboarding, retention, refunds, comms — to new design educators. They all rebuild it badly from scratch.",1,1],
[61,"Guest-Mentor Network","Supply vetted senior mentors to other bootcamps as a service. You broker, you don't teach.",1,1],
[62,"Honest Design School Comparison","India's design education market has no trustworthy comparison layer. Schools pay for qualified leads.",1,1],
[63,"Case-Study Ghostwriting","Other design creators need content constantly. Produce it white-label, on retainer.",1,0],
[64,"Workshop-in-a-Box Licensing","Pre-built workshop kits that corporate trainers and consultants buy and run themselves. You never travel.",1,1],
[65,"Community Infrastructure Ops","Run the backend — events, moderation, sponsorship sales — for other people's design communities, on retainer.",1,1],
[66,"Sponsorship Brokerage","Sell ad slots across a network of small design newsletters and podcasts, take 30%. You own the demand side.",1,1]]},
{L:"G",f:4,t:"Audience-first",w:"Build attention, monetise later — and know it's slow",q:"What would people follow?",i:[
[67,"Enterprise UX Newsletter","A weekly teardown of one complex, boring, high-stakes interface — air traffic control, EMR, trading terminals, factory HMIs. No competition, wealthy readership, obvious sponsor fit, and it qualifies leads for #23.",0,1],
[68,"The Design Roast Podcast","Anonymous portfolio and product roasts. Built-in virality, infinite free material, and the format is already proven in dev and finance.",0,0],
[69,"Gaming × Design Teardowns","Game UI and UX — menus, HUDs, onboarding, difficulty curves. Merges your gaming interest with a genuinely underserved craft niche. Game studios sponsor.",1,0],
[70,"India Design Awards","You create the award. Entries are paid, sponsors pay, and you become the arbiter of quality. Awards are a licence to print status.",1,1],
[71,"Indian Design Salary Report","An annual compensation and layoff report. Becomes the thing everyone cites and links to, forever, for one month of work a year.",0,1],
[72,"\"How They Design\" Series","Inside design at Boeing, ISRO, Zerodha, Tata. Access is your unfair advantage and nobody else can book these rooms.",0,0],
[73,"Enterprise-Only Job Board","No agency spam, only complex-product roles. Companies pay to post; designers browse free.",1,1],
[74,"One Bad Interface a Day","A daily 30-second teardown short. Mechanical, cheap, compounding — and it needs no personality if you don't want to be on camera.",0,1]]},
{L:"H",f:5,t:"Geo, language &amp; regulatory",w:"Vernacular, tier-2/3, cross-border, mandate-driven",q:"Where is the same thing worth more?",i:[
[75,"Hinglish Design Education","Tier-2/3 India, taught in a Hindi-English mix, ₹4,999. All premium design education is in polished English; the market below it is ten times larger and untouched.",0,0],
[76,"Vernacular Design Vocabulary","Teaching design in Marathi, Tamil, Telugu. CSR and grant money genuinely exists for this and almost nobody claims it.",1,0],
[77,"EU → India Talent Bridge","Help European studios hire and manage Indian designers. Fee from the studio, paid in euros. Your Polimi network is the entry point.",1,1],
[78,"India → Global Remote Placement","Get Indian designers into US/EU remote roles and take a fee. The measured gap: skilled freelance UX in India runs <b>₹1,500–4,000/hour</b> against a global experienced rate of <b>$78–138/hour</b>, and international clients reportedly pay <b>2–3×</b> domestic. On salaries, Indian mid-level product design sits around ₹12–25L at product companies. The arbitrage is real; treat 3× as an upper bound for mid-level, not a rule — senior designers at top Indian firms already reach ₹35–55L.",1,1],
[79,"Design for Bharat","UX for low-literacy, low-bandwidth, first-time internet users. A real specialism, and NGOs, banks and government all pay for it.",1,0],
[80,"Accessibility Compliance Practice","The European Accessibility Act deadline was <b>28 June 2025</b>. It binds anyone selling to EU consumers, requires conformance with <b>EN 301 549 / WCAG 2.1 AA</b>, and carries penalties up to <b>€100,000 or 4% of annual revenue</b>. Firms under 10 staff and €2M are exempt — everyone else is now non-compliant or scrambling. Mandate-driven demand with a date attached, and you hold an EU credential.",1,0],
[81,"India Localisation Audits","Global products entering India get an audit of what will break culturally and behaviourally. Fixed fee, highly repeatable, remote.",1,0],
[82,"Milan–India Design Exchange","Paid study tours. Indian designers pay to spend a week inside Milan's design ecosystem, which you can actually open.",0,0],
[83,"The EU Design Job Playbook","How to get a design job in Europe as an Indian — visas, portfolio norms, salary bands, recruiter behaviour. You have literally done this.",0,1],
[84,"Gulf Enterprise Design","Middle-East enterprises are spending heavily on digital, pay in USD-pegged currency, and have almost no local design talent.",1,0]]},
{L:"I",f:3,t:"Newly possible",w:"What changed in the last 24 months and isn't priced in",q:"What was impossible in 2024?",i:[
[85,"AI-Proof Design Practice","For designers watching AI eat UI production: reposition onto judgment, systems and strategy. This is 2026's single most acute career anxiety and almost nobody credible is addressing it.",0,0],
[86,"Design QA for AI-Generated UI","Teams now ship AI-built interfaces fast and badly. Sell the review layer — as a service, then as a rubric, then as a tool.",1,0],
[87,"UX for Agentic Products","How to design when the interface is a conversation and the system acts on its own. There is no established practice yet, which means the first credible curriculum owns the category.",0,0],
[88,"Evals as Design Research","Teach designers to write evals for AI products. It is the new usability testing and design has not yet claimed the territory — a two-year land grab.",0,0],
[89,"The Honest AI Tool Lab","Tested, comparative reviews of AI design tools with real output side-by-side. Every existing directory is affiliate-farmed and untested; trust is the entire moat.",1,1],
[90,"Prompt-to-Prototype Program","From brief to clickable prototype in a day. Employers buy this because it's a measurable productivity claim, not a vibe.",1,0],
[91,"AI Interview Simulator","An AI mock-interviewer for design candidates, with structured feedback. Genuinely buildable by one person now; wasn't in 2024.",0,1],
[92,"Designer Personal-Brand Engine","A system, not an agency, that turns a designer's existing work into publishable content. Delivery cost is now near zero.",0,1],
[93,"Design System Migration","AI makes bulk component migration tractable. Sell the outcome and the fixed fee, never the hours.",1,0],
[94,"Enterprise AI Adoption Design","Large companies bought AI licences and nobody uses them. Design the adoption, not the tool. Aerospace-adjacent enterprises have this exact problem right now and you know who to call.",1,0]]},
{L:"J",f:5,t:"Contrarian &amp; deliberately bad",w:"The round that breaks self-censorship. Two of these are secretly good.",q:"What would be absurd?",i:[
[95,"The Anti-Portfolio School","Teach designers to get hired without a portfolio at all — referrals, writing, proof-of-work in public. Heretical. Also true.",0,0],
[96,"Design Rehab","For burnt-out designers who want to leave design entirely. Charge them to exit gracefully. Deeply uncomfortable, real demand.",0,0],
[97,"The ₹1,00,000 Critique","One absurdly expensive teardown a month, for design leaders only. Pure status pricing — and the price is the marketing.",0,1],
[98,"Roast-for-Hire","Companies pay you to publicly roast their own product as a marketing stunt. Bizarre. Works. Nobody's doing it in India.",1,0],
[99,"Design Court","A mock-trial format where a product is prosecuted and defended before a jury. Ticketed, sponsorable, unforgettable.",1,0],
[100,"Ugly on Purpose","A paid course on deliberately ugly, high-converting design. Anti-taste, and it consistently outperforms beautiful work.",0,0],
[101,"The Bad Design Museum","A curated pop-up exhibition of terrible Indian interfaces. Tickets, press coverage, sponsors, and a permanent content archive.",1,0],
[102,"Designer Fight Club","Two designers, one brief, sixty minutes, live audience vote. Merch, tickets, streaming, format licensing.",0,0],
[103,"Anonymous Design Confessions","A paid publication of what designers actually think about their employers. Legally spicy, enormously readable.",0,1],
[104,"The Quit-Your-Job Cohort","Help other corporate designers do precisely what you are doing, using your own exit as the live curriculum. Your credibility is at its absolute maximum while you're mid-transition — and that window closes in about nine months.",0,0],
[105,"Design Astrology","Deliberately silly: match designers to career paths via a nonsense-but-uncannily-accurate quiz. Pure viral top-of-funnel.",1,1],
[106,"Reverse Bootcamp","Companies pay to be taught by junior designers what they're getting wrong about hiring and managing them. Inverts every assumption in the market.",1,1]]},
{L:"K",f:5,t:"Anti-scale",w:"Deliberately small, high-margin, 20-customers-a-year",q:"What if you never scaled?",i:[
[107,"Twelve Clients a Year","₹5L strategic-design engagements, one a month, no team, no funnel, no scale. ₹60L a year and your evenings back.",0,0],
[108,"The Retained Design Conscience","Three companies, ₹1.5L a month each, you're on call for judgment calls. Location-independent by construction.",1,0],
[109,"Six-Person Mastermind","₹1.5L per person per year, senior designers only, invite-only. Roughly twelve hours of work a month.",0,0],
[110,"One Workshop a Month, Flown In","Corporate design workshop, expenses covered. Corrected figure: specialist corporate training in India bills <b>₹30,000–1.5L per day</b>, so a two-day programme is roughly ₹60,000–3L — not the ₹4–8L I originally asserted. Twelve a year is a real income, not a fortune.",1,0],
[111,"Expert Network Calls","GLG and Third Bridge pay experts by seniority: published bands are <b>$400–600/hr for mid-level specialists and directors</b>, $600–800 for senior executives, $800–1,200+ for C-suite. At your level assume the first band, roughly ₹33,000–50,000 a call — not the $1,000 I implied. Zero marketing, zero product, starts this month.",1,1],
[112,"Fractional Head of Design","One company, two days a week, remote, ₹2.5L a month. Boring, unsexy, and it buys your freedom immediately.",1,0]]}];

const FAST=new Set([6,7,11,12,15,16,22,43,53,97,107,110,111,112]);
