/* ---------- picks ---------- */
const PICK=[
["1","#23 · Enterprise design upskilling for GCCs","The payer has an allocated, expiring budget; you have credibility they can verify in thirty seconds and a network no competitor can buy. One ₹8L contract equals a year of course revenue with one customer to serve instead of two hundred. And it's the only idea in the bank where <b>your Boeing job is the distribution channel</b> rather than the thing you're escaping."],
["2","#85 + #87 + #88 · The AI repositioning trio","Acute, universal, unaddressed anxiety with a hard timing window — twelve months before ten credible people occupy it. Crucially it sits on <b>strategy and judgment</b>, which is your Polimi side and the part AI can't take, rather than on craft, which is the part it already took. Sell it to the #23 buyer and the two ideas compound instead of competing."],
["3","#67 · The enterprise UX newsletter","Not a business — say it plainly, it scores 2 on willingness to pay. But it's the cheapest compounding asset available to you, it has genuinely zero competition, its readers are the exact people who sign #23's cheques, and it costs one Saturday a week. <b>Start it regardless of what else you choose.</b> If you do only one thing from this document, do this one."],
["4","#112 / #53 / #111 · Fractional and advisory work","This is the bridge, not the destination. Cash inside thirty days, no product to build, no audience required, fully remote — it buys you the runway and the nerve to test everything else without your savings draining. Most people skip this and end up rushing a bad launch because rent is due. <b>Take the boring money first.</b>"],
["5","#78 · India → global remote placement","The one pure arbitrage in the bank. You aren't creating value, you're exploiting a structural mispricing between two labour markets, which means the value is self-evident and needs no marketing argument. The buyer pays out of a raise rather than a budget, so the price objection never appears. Hardest to start — you need supply and demand simultaneously — which is why it's fifth and not first."]];
document.getElementById('picks').innerHTML=PICK.map(([r,t,w])=>
 `<div class="pick"><div class="rank">${r}</div><div><div class="pt">${t}</div><div class="pw">${w}</div></div></div>`).join('');

